language: cpp
sudo: false
matrix:
  include:
  - env: ubuntu
    os: linux
    dist: xenial # ubuntu 16.04 LTS
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential
script: make
